### ISSUE TITLE
upstreamed in ebiten main ?

### ISSUE THREAD

**Issue by gedw99** [blizzy78/ebitenui#7]
do you know is this is eventually planned to be upstreamed to ebiten and so supported there ?

**Comment by blizzy78** [comment]
There are currently no plans to integrate this into Ebiten itself. And I currently don't believe it ever will be since Ebiten is supposed to be doing one thing only, according to the author.

**Comment by hajimehoshi** [comment]
Right. I don't plan to integrate a UI library to the Ebiten core as Ebiten should focus on the minimum feature set.

**Comment by Distortions81** [comment]
Sorry, off topic... but I am excited to see golang & ebiten getting more popular.
I was very excited when I discovered ebitenui!
